server {
    listen 127.0.0.1:8083;
    error_page 404 content/error_pages/404.html;
    client_max_body_size 900;

    location / {
        allow_methods GET;
        root /home/ataan/webserv/restFulQuack/content;
        # return 301 https://www.instagram.com/chicken.quack.goose;
        # autoindex on;
        # index index.html;
    }

    location /uploads {
        # return 302 ../index.html;
        allow_methods GET POST DELETE;
        root /home/ataan/webserv/restFulQuack/content/uploads;
        upload_store /home/ataan/webserv/restFulQuack/content/uploads;
        autoindex on;
    }

    location /cgi
    {
        allow_methods GET POST;
        root /home/ataan/webserv/restFulQuack/content/cgi;
        cgi_pass .py /usr/bin/python3; 
    }
}

# http://localhost:8083/secret --> 403 (when no auto-index)
# http://localhost:8083/secrets --> 404 --> custome 404
# if index.html not found --> 404